In [5]:
import pandas as pd

caminho_arquivo= 'cod_material_servico.txt'

df= pd.read_csv(caminho_arquivo,sep=";" )
#df['Data_Inicio_Sintomas'] = pd.to_datetime(df['Data_Inicio_Sintomas'])
df.head()

,cod_item,desc,status,cod_grupo,grupo,cod_classe,classe,cod_classif,classif,material_servico,complex
0,449284,"PECAS / ACESSORIOS ARMAMENTO, MATERIAL ACO TI...",ATIVO,10.0,ARMAMENTO,1005.0,ARMAS DE FOGO DE CALIBRE ATE 120MM,1712.0,PECAS / ACESSORIOS ARMAMENTO,MATERIAL,1.0
1,447288,"PECAS / ACESSORIOS ARMAMENTO, MATERIAL ACO TI...",ATIVO,10.0,ARMAMENTO,1005.0,ARMAS DE FOGO DE CALIBRE ATE 120MM,1712.0,PECAS / ACESSORIOS ARMAMENTO,MATERIAL,1.0
2,236330,"BUCHA PLACA PUNHO, MATERIAL ACO COM ROSCA INTE...",ATIVO,10.0,ARMAMENTO,1005.0,ARMAS DE FOGO DE CALIBRE ATE 120MM,15001.0,BUCHA PLACA PUNHO,MATERIAL,1.0
3,451952,"PECAS / ACESSORIOS ARMAMENTO, MATERIAL METAL ...",ATIVO,10.0,ARMAMENTO,1005.0,ARMAS DE FOGO DE CALIBRE ATE 120MM,1712.0,PECAS / ACESSORIOS ARMAMENTO,MATERIAL,1.0
4,448489,"PECAS / ACESSORIOS ARMAMENTO, MATERIAL ACO TI...",ATIVO,10.0,ARMAMENTO,1005.0,ARMAS DE FOGO DE CALIBRE ATE 120MM,1712.0,PECAS / ACESSORIOS ARMAMENTO,MATERIAL,1.0

In [7]:
caminho_arquivo_1= 'text.txt'
df= pd.read_csv(caminho_arquivo_1,sep=";" )
#df['Data_Inicio_Sintomas'] = pd.to_datetime(df['Data_Inicio_Sintomas'])
df.head()

                                          dsc_item,n
0                                   AGUA SANITARIA,7
1                              BISCOITO AGUA E SAL,4
2                             AGUA MINERAL C/20LT.,3
3  SABAO EM PO  COR AZUL COMPOSTO POR TENSOATIVO ...
4                              AGUA DESTILADA 10ML,2

In [7]:
import re

df['coluna_numerica'] = df['dsc_item'].apply(lambda x: ''.join(re.findall(r'\d+', str(x))))


df.head()

                                            dsc_item  n coluna_numerica
0                                     AGUA SANITARIA  7
1                                BISCOITO AGUA E SAL  4
2                               AGUA MINERAL C/20LT.  3              20
3  SABAO EM PO  COR AZUL COMPOSTO POR TENSOATIVO ...  3          115256
4                                AGUA DESTILADA 10ML  2              10

In [4]:
import pandas as pd
import re

df = pd.read_csv('text.txt')

dsc_item = []
Produto = []
Unidade = []
Tamanho = []

def extrair_informacoes(descricao):
    produto_match = re.search(r'^([\w\s]+)', descricao)
    if produto_match:
        Produto.append(produto_match.group(1))
    else:
        Produto.append(None)

    unidade_match = re.search(r'(\d+\s*[A-Za-z]+)', descricao)
    if unidade_match:
        Unidade.append(unidade_match.group(1))
    else:
        Unidade.append(None)

    tamanho_match = re.search(r'(\d+\s*[A-Za-z\/]+)(?=\s*,|\s*$)', descricao)
    if tamanho_match:
        Tamanho.append(tamanho_match.group(1))
    else:
        Tamanho.append(None)


df['dsc_item'].apply(extrair_informacoes)

df['Produto'] = Produto
df['Unidade'] = Unidade
df['Tamanho'] = Tamanho


print(df[['dsc_item', 'Produto', 'Unidade', 'Tamanho']])

                                              dsc_item  \
0                                       AGUA SANITARIA
1                                  BISCOITO AGUA E SAL
2                                 AGUA MINERAL C/20LT.
3    SABAO EM PO  COR AZUL COMPOSTO POR TENSOATIVO ...
4                                  AGUA DESTILADA 10ML
..                                                 ...
973               UNIAO PVC PARA SOLDA 85 MM AGUA FRIA
974  UNIAO PVC SOLD P/AGUA FRIA PREDIAL 20MM-UN- 00...
975  VALVULA DE RETENCAO EM BRONZE DE 3 POLEGADA HO...
976  VASILHAME PARA AGUA MINERAL (GALAO), COM CAPAC...
977                       VASILHAME, DE AGUA 20 LITROS

                                               Produto     Unidade    Tamanho
0                                       AGUA SANITARIA        None       None
1                                  BISCOITO AGUA E SAL        None       None
2                                       AGUA MINERAL C        20LT       None
3    SABAO EM PO  COR AZUL COMPOSTO POR TENSOATIVO ...        1 KG       None
4                                  AGUA DESTILADA 10ML        10ML       10ML
..                                                 ...         ...        ...
973               UNIAO PVC PARA SOLDA 85 MM AGUA FRIA       85 MM       None
974                                   UNIAO PVC SOLD P        20MM       None
975  VALVULA DE RETENCAO EM BRONZE DE 3 POLEGADA HO...  3 POLEGADA    300 PSI
976                       VASILHAME PARA AGUA MINERAL    20 LITROS  20 LITROS
977                                          VASILHAME   20 LITROS  20 LITROS

[978 rows x 4 columns]

In [5]:

#contagem_nao_nulos = df.count()

# O resultado será uma série que mostra a contagem de valores não nulos em cada coluna
#print(contagem_nao_nulos)

# Salvar o DataFrame em um arquivo TXT com as quatro colunas separadas por ponto e vírgula
df.to_csv('dados.txt', sep=';', index=False, columns=['dsc_item', 'Produto', 'Unidade', 'Tamanho'])